DROP TABLE cinemas CASCADE CONSTRAINTS;
DROP TABLE theaters  CASCADE CONSTRAINTS;
DROP TABLE screenings CASCADE CONSTRAINTS;
DROP TABLE reservations  CASCADE CONSTRAINTS;
DROP TABLE movies CASCADE CONSTRAINTS;
DROP TABLE customers  CASCADE CONSTRAINTS;

CREATE TABLE cinemas (CINEMA_ID VARCHAR(8) primary key,
         		CINEMA_NAME VARCHAR(30) NOT NULL,
			STREET_ADDRESS VARCHAR(30) NOT NULL,
			CINEMA_CITY VARCHAR(20) NOT NULL,
         		CINEMA_STATE VARCHAR(2) NOT NULL,
			CINEMA_PHONE VARCHAR(15) NOT NULL);

CREATE TABLE theaters (THEATER_ID VARCHAR(8) primary key,
			CINEMA_ID VARCHAR(8) NOT NULL,
			CAPACITY NUMBER NOT NULL,
			CONSTRAINTS CINEMA_ID_FK foreign key	
          		(CINEMA_ID) references cinemas (CINEMA_ID));

CREATE TABLE movies (MOVIE_ID VARCHAR(8) primary key,
			MOVIE_NAME VARCHAR(50) NOT NULL,
          		MOVIE_DIRECTOR VARCHAR(40) NOT NULL,
         		RATING CHAR(4) NOT NULL,
          		LENGTH NUMBER NOT NULL,
          		RELEASE_DATE DATE NOT NULL,
          		DESCRIPTION VARCHAR(500) NOT NULL);

CREATE TABLE screenings (SCREENING_ID VARCHAR(8) primary key,
			MOVIE_ID VARCHAR(8) NOT NULL,
			THEATER_ID VARCHAR(8) NOT NULL,
			SCREENING_DATE DATE NOT NULL,
			START_TIME VARCHAR(8) NOT NULL,
          		CONSTRAINTS MOVIE_ID_FK foreign key (MOVIE_ID) references movies (MOVIE_ID),
         		CONSTRAINTS THEATER_ID_FK foreign key 
          		(THEATER_ID) references theaters (THEATER_ID));

CREATE TABLE customers (CUST_ID VARCHAR(8) primary key,
			CUST_NAME VARCHAR(20) NOT NULL,
			CUST_PHONE  VARCHAR(15) unique NOT NULL,
			CUST_EMAIL VARCHAR(40) unique NOT NULL);


CREATE TABLE reservations ( RES_ID VARCHAR(8) primary key,
			CUST_ID VARCHAR(8) NOT NULL,
			SCREENING_ID VARCHAR(8) NOT NULL,
    			SEAT_NO VARCHAR(3), 
    			PRICE DECIMAL (4,2) NOT NULL,
   			CONSTRAINTS CUST_ID_FK foreign key (CUST_ID) 
    			references customers (CUST_ID),
    			CONSTRAINTS SCREENING_ID_FK foreign key 
    			(SCREENING_ID) references screenings (SCREENING_ID));
